online_store/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :cart, controller: 'carts' do
    get 'carts', to: 'cart#show'
    post 'carts/add'
    post 'carts/remove'
  end

  resources :user, :products do
    resources :reviews
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'
  get 'search', to: 'products#search'

  patch 'change_locale' => 'locales#change_locale'

  mount Sidekiq::Web => '/sidekiq'
end

online_store/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, optional: true
  has_many_attached :pictures
  has_many :reviews, as: :reviewable, dependent: :destroy
  has_many :cart_items
  has_many :carts, through: :cart_items

  validates :name, presence: true, length: { minimum: 2 }
  validates :product_detail, presence: true, length: { maximum: 255 }
  validates :price, presence: true
  validates :location, presence: true
  validates :pictures, blob: { content_type: %w[image/png image/jpg image/jpeg], size_range: 1..5.megabytes }
  validates :availability, presence: true, inclusion: { in: ['in stock', 'out of stock'],
                                                        message: '%<value>s is not a valid' }

  scope :in_stock, -> { where(availability: 'in stock') }
end

online_store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include VariableCart
  before_action :authenticate_user!, only: %i[edit create update new destroy show]
  before_action :initialize_cart, only: %i[index]

  def index
    @filter, @products = ProductFilter::Search.call(params)
    if @products.present?
      @products
    else
      redirect_to products_path, notice: 'Not a valid combination'
    end

    @render_cart = true
  end

  def show
    @product, @review, @reviews = ReviewVariable::ProductReview.call(params)
    # fresh_when last_modified: @product.created_at.utc, etag: @product
    # fresh_when last_modified: @review.updated_at, etag: @product.reviews.cache_key_with_version
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    authorize @product

    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    authorize @product

    redirect_to products_path
  end

  private

  def initialize_cart
    load_variable_cart
  end

  def product_params
    params.require(:product).permit(:name, :category, :product_detail, :price, :location, :availability, :user_id,
                                    pictures: []).merge(user_id: current_user.id)
  end
end

online_store/app/helpers/products_helper.rb
module ProductsHelper
end

online_store/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :product_detail, style: "display: block" %>
    <%= form.text_field :product_detail %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :availability, style: "display: block" %>
    <%= form.text_field :availability %>
  </div>

   <div>
    <%= form.label :pictures, style: "display: block" %> 
    <%= form.file_field :pictures, multiple: true %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

online_store/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category %>
  </p>

  <p>
    <strong>Product detail:</strong>
    <%= product.product_detail %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= product.location %>
  </p>

  <p>
    <strong>Availability:</strong>
    <%= product.availability %>
  </p>

  <div>
    <% product.pictures.each do |picture| %>
      <%= link_to image_tag(picture.variant(resize_to_limit: [150, 150])), picture %>
    <% end %>
  <div/>

  <%= form_with(url: carts_add_path) do |f| %>
    <%= f.hidden_field :id, value: product.id %>
    <%= f.number_field :quantity, value: 0, min: 1 %>
    <%= f.submit "Add To Cart" %>
  <% end %>

</div>

online_store/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

online_store/app/views/products/index.html.erb
<%= search_form_for @filter, class: "form-inline my-2 d-flex" do |f| %>
  <%= f.search_field :name_or_location_cont, placeholder: 'Search', class: "form-control me-2" %>
  <%= f.submit 'Search', class: "btn btn-outline-success" %>
  <%= link_to "Back to products", products_path, class: 'btn btn-info btn-sm' %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@filter, :name, "Name", default_order: :asc) %></th>
      <th><%= sort_link(@filter, :location, "Location", default_order: :desc) %></th>
      <th><%= sort_link(@filter, :price, "Price", default_order: :desc) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>

<h1>
<%= I18n.t(:products) %>
</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

 

online_store/app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

online_store/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Back to products", products_path %>
    <% if policy(@product).update?%>

      <%= link_to "Edit this product", edit_product_path(@product) %> |
      <%= button_to "Destroy this product", @product, method: :delete %>
    <% end %>
</div>

<%= form_with model: [@product, @review] do |form| %>
  <% if @review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<h2> Reviews <h2>

<% @reviews.each do |review| %>

  <p>
  <%= review.body %>
  <%= review.rating %>
  <p>

   <%= link_to "Edit this review", edit_product_review_path(@product, review) %> 
  
  <% if policy(@review).destroy? %>
    <%= button_to "Destroy this review", product_review_path(@product, review), method: :delete %>
  <% end %>

<% end %>