online_store/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :cart, controller: 'carts' do
    get 'carts', to: 'cart#show'
    post 'carts/add'
    post 'carts/remove'
  end

  resources :user, :products do
    resources :reviews
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'
  get 'search', to: 'products#search'

  patch 'change_locale' => 'locales#change_locale'

  mount Sidekiq::Web => '/sidekiq'
end

online_store/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user

  def total
    cart_items.to_a.sum { |cart_items| cart_items.total }
  end
end

online_store/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include VariableCart
  before_action :authenticate_user!
  before_action :initialize_cart, only: %i[add]

  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_cart_item = @cart.cart_items.find_by(product_id: @product.id)
    if current_cart_item && quantity.positive? && @product
      current_cart_item.update(quantity:)
    elsif quantity <= 0
      current_cart_item.destroy
    else
      @cart.cart_items.create(product: @product, quantity:)
      redirect_to carts_path
    end
  end

  def remove
    CartItem.find(params[:id]).destroy
    redirect_to carts_path
  end

  private

  def initialize_cart
    load_variable_cart
  end
end

online_store/app/helpers/carts_helper.rb
module CartsHelper
end

online_store/app/views/carts/_cart.html.erb
<h1>Carts</h1>
<% if @cart.cart_items.count > 0 %>
  <%= render "carts/cart_items" %>
  <p>Total: <%= @cart.total %>
  <% else %>
  <p>Your cart is empty <p>
<% end%>

online_store/app/views/carts/_cart_items.html.erb
<% @cart.cart_items.each do |cart_item| %>
  <% product = cart_item.product %>

    <div id="<%= "cart-#{product.id}" %>">
    <p>
      <strong>Name:</strong>
      <%= product.name %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= product.category %>
    </p>

    <p>
      <strong>Product detail:</strong>
      <%= product.product_detail %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= product.price %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= product.location %>
    </p>

    <p>
      <strong>Availability:</strong>
      <%= product.availability %>
    </p>

    <div>
      <% product.pictures.each do |picture| %>
        <%= link_to image_tag(picture.variant(resize_to_limit: [150, 150])), picture %>
      <% end %>
    <div/>

    <%= form_with(url: carts_add_path) do |f| %>
      <%= f.hidden_field :id, value: product.id %>
      <%= f.number_field :quantity, value: cart_item.quantity, min: 0 %>
      <%= f.submit "Add To Cart" %>
    <% end %>

     <%= form_with(url: carts_remove_path) do |f| %>
      <%= f.hidden_field :id, value: cart_item.id %>
      <%= f.submit "Dellet to cart" %>
    <% end %>

    <%= form_with(url: carts_remove_path) do |f| %>
      <%= f.hidden_field :id, value: cart_item.id %>
      <%= f.submit "Buy" %>
    <% end %>

    <strong>Total:<strong>
    <%= cart_item.total %>
<% end %>

online_store/app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>