online_store/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope :cart, controller: 'carts' do
    get 'carts', to: 'cart#show'
    post 'carts/add'
    post 'carts/remove'
  end

  resources :user, :products do
    resources :reviews
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'
  get 'search', to: 'products#search'

  patch 'change_locale' => 'locales#change_locale'

  mount Sidekiq::Web => '/sidekiq'
end

online_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineMarketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
      <div>
      <% if user_signed_in? %>
        <%= link_to "Edit Account", edit_user_registration_path(current_user) %>
        <%= current_user.email %>
        <% if current_user.avatar.attached? %>
          <%= image_tag(current_user.avatar.variant(resize_to_limit: [100, 100])) %>
        <% end %>
        <%= link_to "Log out", destroy_user_session_path, data: { 'turbo-method': :delete } %>
      <% else %>
        <%= link_to "Log in", new_user_session_path %>
      <% end %>
    </div>
    

    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <%= render partial: "carts/cart" if @render_cart%>


    <%= yield %>


    <footer>
      <% if user_signed_in? %>
        <%= I18n.t('locale.change') %>
        <% User::AVAILABLE_LOCALES.each do |locale| %>
          <% next if locale == I18n.locale.to_s %>

          <%= button_to locale, change_locale_path, params: { locale: locale }, method: :patch %>
        <% end %>
      <% end %>
    </footer>
  </body>
</html>